# Generated by Django 4.0.2 on 2023-09-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
