# Generated by Django 4.0.2 on 2023-09-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='different_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
